# Ejercicios notebook 7

**Ejercicio: Investigar y ejemplificar diferencias entre np.array y np.matrix**

### np.array

Crea un array

In [2]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

Podemos crear matrices con np.array

In [4]:
a = np.zeros((2, 3))

In [6]:
print(a)
a.shape

[[0. 0. 0.]
 [0. 0. 0.]]


(2, 3)

Pero hay operaciones que solo se pueden usar para np.array como  **np.linspace**

In [7]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

Tambien podemos convertir una lista de python a un array de numpy con **np.array**

In [24]:
lst = [1,1,1,1,1,1]
np.array(lst)

array([1, 1, 1, 1, 1, 1])

Podemos usar **np.arange** para crear un vector apartir de una serie de numeros, esto es exlusivo para np.array

In [233]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### np.matrix

Crea una matriz

In [218]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

Hay operaciones sobre especificamente sobre matrices como la  matriz identidad usando **np.identity**

In [227]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Tambien la inversa de una matriz con **matrix.getI()**

In [221]:
x = np.matrix([[1, 2], [3, 4]])
x.getI()

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

O la transpuesta de una matriz con **x.getT()**

In [222]:
x.getT()

matrix([[1, 3],
        [2, 4]])

# Ejercicios notebook 8

**Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:**

In [223]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    return 1/(1+np.exp(-x))

In [224]:
def neural_network(x):
    CAPA_1 = np.array([[0.712,0.355,0.268], [0.112,0.855,0.468]])
    CAPA_2 = np.array([0.116, 0.329, 0.708])
    H1 =  sigmoid(np.matmul(x, CAPA_1))
    return sigmoid(np.matmul(H1, CAPA_2))

### Prueba 1

In [225]:
x = np.array([1,1])
neural_network(x)

0.6926955296507851

### Prueba 2

In [226]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

In [214]:
neural_network(X)

array([0.70244573, 0.66259284, 0.75933678, 0.75973948, 0.75802295,
       0.6739704 , 0.75954693, 0.76005845, 0.75952743, 0.76005845])